### ISSUE TITLE
Configuration error while running program

### ISSUE THREAD

**Issue by kangarax** [bbayles/vod_metadata#1]
Nothing i could input under provider_id works.

Tried:
example.com (the one included in the default zip)
www.example.com
www.bskyb.com
bskyb.com
bskyb

any domain .net/.com/co.uk, etc...

![3](https://cloud.githubusercontent.com/assets/3680412/6287883/dce0b7a2-b90c-11e4-9ca3-822657da0b8a.png)

**Comment by bbayles** [comment]
Could you switch back to using the default configuration file and try again? Could you also upload the .ini file you are using?

**Comment by kangarax** [comment]
Hi and sorry for the delay, data attached.

![2](https://cloud.githubusercontent.com/assets/3680412/6368294/3db106e4-bcd3-11e4-8e6f-56d56654bea8.png)
![template_1](https://cloud.githubusercontent.com/assets/3680412/6368295/3db5321e-bcd3-11e4-9032-7d85de785b93.png)

**Comment by bbayles** [comment]
Not sure what's going on. Could you delete the `provider_id` line entirely?

I am working on a new branch that I might have you [try out](https://github.com/bbayles/vod_metadata/compare/pep8).

**Comment by kangarax** [comment]
Hi!,
 tried the following:
comment provider_Id line such as this:

# VOD asset elements are identified by provider_id / asset_id pairs
# provider_id must be a "registered internet domain name restricted to at most
# 20 lower - case characters and belonging to the provider"
# prefix will start each asset_id identifier. It must be three characters
# provider_id = example.net

and removed it entirely, still same error.

What I'll try to do over the week end is install the code on Linux and see if it's by any chance an issue specific with Windows (don't know, maybe encoding and/or I've added characters like newline/tab,etc... on provider_id line that's causing the issue?)

![1](https://cloud.githubusercontent.com/assets/3680412/6411744/8c406f74-be73-11e4-99f6-8d8109770382.png)

**Comment by bbayles** [comment]
I'm really not sure... I initially developed and tested this on Windows 7 and 2003. I tested Win8 earlier this week.

I will push a new version to Pypi that gives a better indication of what's up.

**Comment by bbayles** [comment]
I uploaded a new version [to Pypi](https://pypi.python.org/pypi?:action=display&name=vod_metadata&version=2015.3.2) - could you try upgrading?

`C:\Python34\python.exe -m pip install vod_metadata --upgrade`

**Comment by kangarax** [comment]
Ok, issue got fixed, now follow-up issue: it can't find the MediaInfo.

Location of Mediainfo.exe is C:\Users\FBU02\Desktop\MediaInfo

MediaInfo.path details:

C:\Users\FBU02\Desktop\MediaInfo\MediaInfo.exe
C:\Users\FBU02\Desktop\MediaInfo

Error:

![2](https://cloud.githubusercontent.com/assets/3680412/6460219/35fd3a1c-c18d-11e4-954d-679d1fe0dcfe.png)

**Comment by bbayles** [comment]
What happens if you run `C:\Users\FBU02\Desktop\MediaInfo\MediaInfo.exe` from the command line? Does a GUI pop up? If so, you need the CLI version.

**Comment by kangarax** [comment]
Downloaded CLI version
re-did the upgrade command you mentioned.
Modified metadata.pth file to:

C:\Users\FBU02\Desktop\MediaInfo_CLI\MediaInfo.exe
C:\Users\FBU02\Desktop\MediaInfo_CLI

Same error..

**Comment by bbayles** [comment]
If you do `C:\Users\FBU02\Desktop\MediaInfo_CLI\MediaInfo.exe` at the command prompt, what do you get now? Can you post a screenshot?

**Comment by kangarax** [comment]
​

**Comment by bbayles** [comment]
Your e-mail reply didn't show what you intended, I think?

**Comment by kangarax** [comment]
Sorry, attached
![untitled](https://cloud.githubusercontent.com/assets/3680412/6555243/fc136dfc-c65b-11e4-931c-3eb4b9fa1ea5.png)

**Comment by bbayles** [comment]
The only thing I can think of is that the `MediaInfo.pth` file isn't getting updated... I re-created your setup exactly.

Everything works for me, though. What do you get when you do __`type C:\Python34\Lib\site-packages\vod_metadata\MediaInfo.pth`__? Mine shows:
```
C:\Users\FBU02\Desktop\MediaInfo_CLI\MediaInfo.exe
C:\Users\FBU02\Desktop\MediaInfo_CLI
```

Here's my command line matching yours:
```
C:\Users\FBU02\Desktop\MediaInfo_CLI>cd C:\Users\FBU02\Desktop\MediaInfo_CLI

C:\Users\FBU02\Desktop\MediaInfo_CLI>dir
 Volume in drive C has no label.
 Volume Serial Number is F06E-509C

 Directory of C:\Users\FBU02\Desktop\MediaInfo_CLI

03/11/2015  08:46 PM    <DIR>          .
03/11/2015  08:46 PM    <DIR>          ..
03/11/2015  08:46 PM    <DIR>          Contrib
01/07/2015  07:01 AM            98,946 History.txt
03/10/2014  08:16 AM             4,249 License.html
01/07/2015  09:53 AM         3,910,480 MediaInfo.dll
01/07/2015  09:53 AM           230,736 MediaInfo.exe
03/11/2015  08:46 PM    <DIR>          Plugin
07/04/2013  04:10 PM               261 ReadMe.txt
               5 File(s)      4,244,672 bytes
               4 Dir(s)  317,474,775,040 bytes free

C:\Users\FBU02\Desktop\MediaInfo_CLI>MediaInfo.exe
Usage: "MediaInfo [-Options...] FileName1 [Filename2...]"
"MediaInfo --Help" for displaying more information
```

**Comment by bbayles** [comment]
@kangarax , I have merged into the master branch a new set of features that lets you specify a path to MediaInfo on the command line. Could you try it out? Check the README for details.

I will push it to pip shortly.

**Comment by kangarax** [comment]
Happy to help, let me know when to update the package,
F.

**Comment by bbayles** [comment]
The package is now updated on PyPI; you may give it a shot.

**Comment by kangarax** [comment]
Initial findings:

1) My vod-metada is installed under C:\vod_metadata-master, however the calls are being made to C:\Python34\Lib\site-packages\vod_metadata.

2) Under C:\Python34\Lib\site-packages I have both vod_metadata and vod_metadata-2015.3.14.dist-info

3) The files for which I need to extract metadata are .mxf files (source files used by broadcasters) and apparently the codec cannot be read/parsed.(error attached)

However,

if I right click the mxf file and use MediaInfo (GUI, not CLI) I do get metadata 

error screenshot attached.

![error](https://cloud.githubusercontent.com/assets/3680412/6666531/3e78a924-cbdd-11e4-943b-af1e1accb020.png)

**Comment by bbayles** [comment]
Looks like progress, at least.

The [CableLabs spec](http://cablelabs.com/wp-content/uploads/specdocs/MD-SP-VOD-CONTENT1.1-C01-120803.pdf), at least the 1.1 version revised in 2012, only defines a few formats.

Can you switch to the MediaInfo CLI directory, then do `mediainfo.exe C:\Path\To\Your\File.mxf`? You may e-mail it to me (my username at gmail.com) if you prefer.

**Comment by kangarax** [comment]
![screen_1_mediainfo_cli_3](https://cloud.githubusercontent.com/assets/3680412/6666752/5c2a9d0e-cbdf-11e4-926a-296dfff910be.png)
![screen_1_mediainfo_cli_2](https://cloud.githubusercontent.com/assets/3680412/6666753/5c2da558-cbdf-11e4-8a61-11052decff47.png)
![screen_1_mediainfo_cli_1](https://cloud.githubusercontent.com/assets/3680412/6666754/5c309bfa-cbdf-11e4-9ee4-ec874759f66c.png)

**Comment by bbayles** [comment]
OK, thanks. I can make it so that the metadata generator doesn't give an error, but there will be no guarantee that a downstream VOD system would accept the result.

**Comment by kangarax** [comment]
It's a test environment for a major broadcast, I just need access to MXF
information in XML so that I can populate some test systems for automation
:)

**Comment by bbayles** [comment]
I pushed a new version to PyPI. This should avoid trying to determine the codec by default, which should prevent your error. Only systems that require the ECN 2009 parameters need the codec and such anyway, so this is probably a good thing to do in general.

**Comment by kangarax** [comment]
Progress!

![progress](https://cloud.githubusercontent.com/assets/3680412/6684994/2f0e389e-cc8e-11e4-85bc-343b87fb5a22.png)

**Comment by bbayles** [comment]
Does it do the same thing if you do: `C:\Python34\python.exe -m vod_metadata --mediainfo-dir "C:\Users\FBU02\Desktop\MediaInfo_CLI\MediaInfo.exe"`?

**Comment by kangarax** [comment]
Unrecognized argument --mediainfo-dir in main.py

**Comment by bbayles** [comment]
Sorry, my fault. The switch is `--mediainfo-path`.

**Comment by kangarax** [comment]
Success!!!

**Comment by bbayles** [comment]
I'll close this issue, then. Thanks for the feedback - let me know how things work for you.
