### ISSUE TITLE
CableLabs Metadata generator 

### ISSUE THREAD

**Issue by nkapowski** [bbayles/vod_metadata#14]
Hi,

I have downloaded you Python generator in order to test its usage.
Each time when I run it, it failed with MediaInfo error.
    mpeg_info = check_video(ae_path, self.vod_config.mediainfo_path)
  File "C:\Users\natalie\AppData\Local\Programs\Python\Python35-32\lib\site-packages\vod_metadata\media_info.py", line 62, in check_video
    raise MediaInfoError(err_msg)
vod_metadata.media_info.MediaInfoError: Could not determine all video paramters
When vod_metadata opens MediaInfo program, what I should do? Just close it?
Can i call you? Thanks in advance for your help.
My mail is natalie@latto.tv

**Comment by bbayles** [comment]
My suspicious is that you've downloaded the GUI version of MediaInfo instead of the CLI version. Could you try to uninstall MediaInfo and re-install the CLI version from [this page](https://mediaarea.net/en/MediaInfo/Download/Windows)?

**Comment by nkapowski** [comment]
Hi dear friend, 
since I don't know your name :-)
Thanks for tip, your guess was right, once CLI version was installed metadata xml get generated! 
 I had to install it in default path you defined, change in vod_config.ini didn't work.
By the chance, do you have any experience in vod 1.1 to 3.0 conversion?  I need also some UI to edit&generate metadata. Do you think this tool you've created could be enhanced and could be used for that purpose? 
I looked on Metadata Generator Pro, but it is looks not exactly fit CableLabs metadata format.

Thanks in advance for your help!

**Comment by bbayles** [comment]
Thanks for confirming that the CLI version works. I will check on `vod_config.ini` and path specification before I close this issue.

Re: 3.0 metadata, I'm no longer in the VOD industry; I would need someone or some organization sponsor 3.0 development, to provide test files and systems, etc.

Re: GUI, I may add one in the future, and would be open to someone contributing one. I don't have plans to do it right now, however.

**Comment by nkapowski** [comment]
Can I change sources you created and use it with changes?

**Comment by bbayles** [comment]
I checked that modifying the path to MediaInfo in `vod_config.ini` works in Windows; I'll close this issue now.

> Can I change sources you created and use it with changes? 

I think you're asking whether you can modify the source code to the application and then use it? The answer is yes, but GitHub issues aren't the place to do tutorials on basic script editing. If you have a question about how to change output you may e-mail me about that.
