### ISSUE TITLE
metadata_template.xml modification

### ISSUE THREAD

**Issue by cihnet** [bbayles/vod_metadata#2]
Hi Bo,

After I make some modifications in "metadata_template.xml" in 

/usr/local/lib/python2.7/dist-packages/vod_metadata-2015.3.2-py2.7.egg/vod_metadata

and running app it still creates .xml with old template

can you please advise?

**Comment by bbayles** [comment]
I don't recommend editing that file, but if you must, you can find the right file to edit as follows:
```
>>> import vod_metadata
>>> vod_metadata.find_data_file("metadata_template.xml")
'/usr/local/lib/python2.7/dist-packages/vod_metadata/metadata_template.xml'
```

**Comment by bbayles** [comment]
I suppose I should also ask what you're trying to accomplish by editing the file? It may be possible to do it without resorting to that.

**Comment by cihnet** [comment]
Hi Bo,

I'm trying to get something like this attachement
Thanks

W dniu 2015-03-22 o 04:37, Bo Bayles pisze:

**Comment by bbayles** [comment]
I don't think attachments work in Github. Could you e-mail it to me? My address is my user name at Gmail.

**Comment by bbayles** [comment]
@cihnet, did my suggestion for for you? If so I will close this issue.
